Fixed the following compilation error under FreeBSD, by adding a newline character at the end of the StringTokenizer.cpp file:
scons: Building targets ...
  CXX     lib/libparse/StringTokenizer.o
lib/libparse/StringTokenizer.cpp:227:2: error: no newline at end of file
scons: *** [lib/libparse/StringTokenizer.o] Error 1
scons: building terminated because of errors.



git-svn-id: https://freenos.googlecode.com/svn/trunk@118 824000e8-63cf-11de-a6e1-e33d94ba4d19