Fixed compilation under at least FreeBSD 7.2-RELEASE. The following warning has been corrected:
 /LinnCreate.cpp:75: error: invalid conversion from 'void*' to 'time_t*'

Additionally, the '&>' has been removed from system(), as it
seemed to break on FreeBSD's default shell, possibly interpreting
'&' to fork it onto the background.



git-svn-id: https://freenos.googlecode.com/svn/trunk@227 824000e8-63cf-11de-a6e1-e33d94ba4d19